# Generated by Django 5.0.14 on 2026-03-18 19:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codpro', models.CharField(max_length=14)),
                ('codder', models.CharField(max_length=7)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['codpro', 'codder'],
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_code', models.CharField(max_length=14)),
                ('chemical_description', models.CharField(max_length=100)),
                ('percentual', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'ordering': ['formula_version_id', 'chemical_code'],
            },
        ),
        migrations.CreateModel(
            name='FormulaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('used_in_reconciliation', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['formula_id', '-start_date', '-version_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('codpro', 'codder'), name='uniq_formula_codpro_codder'),
        ),
        migrations.AddField(
            model_name='formulaversion',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='formulaitem',
            name='formula_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='formulas.formulaversion'),
        ),
        migrations.AddIndex(
            model_name='formulaversion',
            index=models.Index(fields=['formula', 'start_date', 'end_date'], name='idx_formula_validity'),
        ),
        migrations.AddConstraint(
            model_name='formulaversion',
            constraint=models.UniqueConstraint(fields=('formula', 'version_number'), name='uniq_formula_version_number'),
        ),
        migrations.AddConstraint(
            model_name='formulaitem',
            constraint=models.UniqueConstraint(fields=('formula_version', 'chemical_code'), name='uniq_formula_version_chemical'),
        ),
    ]
