# Generated by Django 5.0.14 on 2026-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaitem',
            name='incomplete_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulaitem',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulaitem',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
