# Generated by Django 5.0.14 on 2026-03-19 19:51

import django.db.models.deletion
from django.db import migrations, models


def link_existing_formulas_to_articles(apps, schema_editor):
    Formula = apps.get_model("formulas", "Formula")
    ArticleCatalog = apps.get_model("catalog", "ArticleCatalog")

    for formula in Formula.objects.filter(article__isnull=True).iterator():
        article = ArticleCatalog.objects.filter(
            codpro=formula.codpro,
            codder=formula.codder,
            active=True,
        ).first()
        if article:
            formula.article_id = article.id
            formula.save(update_fields=["article"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('formulas', '0002_formulaitem_incomplete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas', to='catalog.articlecatalog'),
        ),
        migrations.RunPython(link_existing_formulas_to_articles, migrations.RunPython.noop),
    ]
