# Generated by Django 5.0.14 on 2026-03-18 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codpro', models.CharField(max_length=14)),
                ('codder', models.CharField(max_length=7)),
                ('article_description', models.CharField(max_length=100)),
                ('derivation_description', models.CharField(max_length=50)),
                ('source_last_seen_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['codpro', 'codder'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_code', models.CharField(max_length=14, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('family_code', models.CharField(blank=True, max_length=6, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=3, null=True)),
                ('product_type', models.CharField(blank=True, max_length=2, null=True)),
                ('product_type_description', models.CharField(blank=True, max_length=15, null=True)),
                ('source_status', models.CharField(blank=True, max_length=5, null=True)),
                ('source_last_seen_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['chemical_code'],
            },
        ),
        migrations.CreateModel(
            name='SyncJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(default='manual', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('records_articles_upserted', models.IntegerField(default=0)),
                ('records_products_upserted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='articlecatalog',
            constraint=models.UniqueConstraint(fields=('codpro', 'codder'), name='uniq_article_catalog'),
        ),
        migrations.AddField(
            model_name='syncjobrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
