# Generated by Django 5.0.14 on 2026-03-18 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulas', '0002_formulaitem_incomplete_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('nf1', models.CharField(blank=True, max_length=9, null=True)),
                ('codpro', models.CharField(blank=True, max_length=14, null=True)),
                ('codder', models.CharField(blank=True, max_length=7, null=True)),
                ('chemical_code', models.CharField(blank=True, max_length=14, null=True)),
                ('only_divergences', models.BooleanField(default=False)),
                ('only_inconsistencies', models.BooleanField(default=False)),
                ('status', models.CharField(default='success', max_length=20)),
                ('processed_lots', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf1', models.CharField(max_length=9)),
                ('recurtimento_date', models.DateField()),
                ('codpro', models.CharField(max_length=14)),
                ('codder', models.CharField(max_length=7)),
                ('lot_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_final', models.CharField(max_length=20)),
                ('has_inconsistency', models.BooleanField(default=False)),
                ('has_divergence', models.BooleanField(default=False)),
                ('items_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formula_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.formulaversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['nf1'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf1', models.CharField(max_length=9)),
                ('chemical_code', models.CharField(max_length=14)),
                ('chemical_description', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('used_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deviation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolerance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_calculated', models.CharField(max_length=20)),
                ('status_reviewed', models.CharField(blank=True, max_length=20, null=True)),
                ('status_final', models.CharField(max_length=20)),
                ('inconsistency_code', models.CharField(blank=True, max_length=50, null=True)),
                ('inconsistency_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formula_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.formulaitem')),
                ('formula_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.formulaversion')),
                ('lot_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.reconciliationlotresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['nf1', 'chemical_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationlotresult',
            constraint=models.UniqueConstraint(fields=('run', 'nf1'), name='uniq_run_nf1'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationitemresult',
            constraint=models.UniqueConstraint(fields=('run', 'nf1', 'chemical_code'), name='uniq_run_nf1_chemical'),
        ),
    ]
