# Generated by Django 5.0.14 on 2026-03-18 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('reviewed_status', models.CharField(max_length=20)),
                ('justification', models.CharField(max_length=500)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('item_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reconciliation.reconciliationitemresult')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reviewed_at', 'id'],
            },
        ),
    ]
