Write-Host "== ChemAnalytics backend bootstrap =="
Write-Host "1. python -m venv .venv"
Write-Host "2. .\\.venv\\Scripts\\Activate.ps1"
Write-Host "3. pip install -r backend\\requirements.txt"
Write-Host "4. python backend\\manage.py migrate"
Write-Host "5. python backend\\manage.py runserver"
Write-Host ""
Write-Host "Dependencias de Oracle/MySQL ficam para fases posteriores:"
Write-Host "pip install -r backend\\requirements-integration.txt"
